name: Test and deploy the agent

on:
  push:
    branches: [main]

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
  AGENT_WORKDIR: ${{ vars.AGENT_WORKDIR }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest update
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create virtual environment
      run: |
        python -m venv ./venv
        source ./venv/bin/activate

    - name: Set up template test
      run: python scripts/setup-template-test.py

    - name: Test the tools
      working-directory: ${{ env.AGENT_WORKDIR }}
      run: poetry run pytest -r 'fEsxX' tests/

    - name: Invoke agent template
      working-directory: ${{ env.AGENT_WORKDIR }}
      run: watsonx-ai template invoke "Hello, how can you help me?"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout latest update
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create virtual environment
      run: |
        python -m venv ./venv
        source ./venv/bin/activate

    - name: Set up deployment config
      env:
        WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY }}
        WATSONX_URL: ${{ secrets.WATSONX_URL }}
        WATSONX_SPACE_ID: ${{ secrets.WATSONX_SPACE_ID }}
      run: python scripts/setup-agent-deployment.py

    - name: Deploy agent to deployment space
      working-directory: ${{ env.AGENT_WORKDIR }}
      run: watsonx-ai service new

    - name: Invoke agent deployment
      working-directory: ${{ env.AGENT_WORKDIR }}
      run: watsonx-ai service invoke "Hello, how can you help me?"
